### ISSUE TITLE
Announcement Feautre

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/discord-bot#145]
### Tasks to Implement:
- [x] **Implement rate limit system**
- [x] **Send message to channel  + Refactor send private message (if needed)**
- [x] **Integrate the code with the queues**

### References:
-   [Announcement ](https://www.notion.so/rndadocs/Announcements-API-Discord-Bot-070b260aa7db43e1ab278b01a0f6514b )
