### ISSUE TITLE
Implement roleDelete, channelDelete, and guildMember Events

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/discord-bot#96]
### Description:
To continue enhancing our Discord bot's capabilities and ensure synchronization with our database, we need to implement roleDelete, channelDelete, and guildMemberRemove events. These events will allow us to remove Role, Channel, and Guild Member entries from the database when a role or channel is deleted on Discord.

### Extra Notes:
For the **roleDelete** event, implementing the delete event directly is straightforward. However, for the **channelDelete** event, we may face a potential issue in the future because currently, each rawInfo contains both channelId and channelName. If we want to use the channelId to get the deleted channel data from the channel collection, we will encounter an error.

A simple solution is to add a **isDeleted** (boolean) field to the channel collection. Instead of deleting the channel entry, we can modify the isDeleted field. When we call the server for the channel list API, if **isDeleted** is true, we will skip that channel. This way, no changes are needed from the UI.

### Tasks to Implement:
- [x] **Implement roleDelete event and delete the corresponding entry in the database**
- [x] **Implement channelDelete event and delete the corresponding entry in the database**
- [x] **Implement guildMemberRemove event and delete the corresponding entry in the database**

### References:
-   [channelDelete](https://old.discordjs.dev/#/docs/discord.js/14.11.0/class/Client?scrollTo=e-channelDelete)
-   [roleDelete](https://old.discordjs.dev/#/docs/discord.js/14.11.0/class/Client?scrollTo=e-roleDelete)
-   [guildMemberRemove ](https://old.discordjs.dev/#/docs/discord.js/14.11.0/class/Client?scrollTo=e-guildMemberRemove )
